### ISSUE TITLE
Missing manifest.yml

### ISSUE THREAD

**Issue by Freed-Wu** [maggie-j-liu/gh-star#1]
Any github-cli plugin must have a `manifest.yml` to store some meta information. Can this plugin add it?

Thanks.

**Comment by maggie-j-liu** [comment]
Hi! I don't see anything in the [docs](https://docs.github.com/en/github-cli/github-cli/creating-github-cli-extensions) that mentions a `manifest.yml`, can you link me to where it says a `manifest.yml` is required?

**Comment by Freed-Wu** [comment]
Seems it is not necessary. `:)`
